### PR TITLE
Asterisk 12-14 compatibility

### PR DESCRIPTION
**Pull request by thomasvargiu**
Asterisk >= 12 compatibility.

- Removed case-insensitive variables (I don't think could be a BC break, it was a bug for asterisk >= 12. Using it in Asterisk < 12 doesn't change nothing)
- Added methods for new headers in events, deprecated the older ones.
- Added other actions and events

### CODE REVIEW

**Comment by thomasvargiu** [comment]
@marcelog This PR are changes based on the official Asterisk [Documentation](https://wiki.asterisk.org/wiki/display/AST/Upgrading+to+Asterisk+12) and my usage on Asterisk 12.

**Comment by marcelog** [comment]
Hi @thomasvargiu,

Thanks for the pull!

I'd like to merge, but it seems there are quite a lot of things in here (18 commits and 39 files changed with mixed cleanups, new stuff, changes, updates, etc), and would like to split it in different pulls so we can trace the changes appropriately later on. Pulls should ideally be very specific.

Could you open different pulls then for the different things? We can incrementally add all your changes (and discuss them if needed) in each pull.

Thank you!

Best regards,

**Comment by thomasvargiu** [comment]
Hi @marcelog,

Yes, I could cherry-pick the commits and open different PRs.
I'm going to do it in the next two days.

**Comment by marcelog** [comment]
Closing this one in favor of the other pulls. Thank you @thomasvargiu!

**Pull request closed without merging**
