### PR TITLE
Response factory

### PR DESCRIPTION
**Pull request by dkgroot**
Added ResponseFactory
 - Merged in origin/timeout branch to solve timeout issues (ed4f296 in seperate Pull Request)
 - Allows you to setResponseHandler("MyDefaultHandler") from MyMessageAction.php
 - Searches for Response with the same name as the Action /PAMI/Message/Action/TestAction -> /PAMI/Message/Response/TestResponse
 - Falls back to GenericResponse Handler (Like UnknownEvent) This will make it easier for people to extend the handling of ResponseMessage.php without having to change this file.
 - Added logging to both factory classes, so we can see what they produce. (Had to change the static function to a public function. Never being called with :: anyway .)

Added InputSanitizer

 - IncomingMessage Keys are pushed through sanitizer
 - Values are stored in the native type (integer / boolean / string / etc)
 - May have to be made optional (improvement / API backward compatibility)

Fixes:
    Sometime now() can be ahead of Message CreationTime, by the time we are asserting (slow machine)

Cleanup:
    Move eventTranslatedValues down

### CODE REVIEW

**Comment by dkgroot** [comment]
Before you ask
src/mg/PAMI/Client/Impl/ClientImpl.php:360
$response = $this->_responseFactory->createFromRaw($msg, $this->_lastActionClass, $this->_lastRequestedResponseHandler)

Can be reduced to:
$response = $this->_responseFactory->createFromRaw($msg, $this->_lastActionClass)
because that information is available within lastActionClass. I had some trouble mocking this and therefor testing. I would need a little help with that one.

**Comment by jacobkiers** [comment]
It seems that this branch is merged with a couple of other branches. That gives me trouble when reviewing it, as I cannot easily find out which parts are actually relevant for this PR and which are not.

Could you therefore please rip out everything that has not directly to do with what you are trying to achieve in this PR? Alternatively, if you don't know how to do that, you can create a new PR with just the Reponse Factory changes.

Git is very good at handling merges, so if someone has to merge multiple branches later on, that's easy.

Thanks!

**Comment by dkgroot** [comment]
I will rip this out later, currently very time contraint.

**Comment by marcelog** [comment]
also: please try to not commit identation changes (although we could use w=1, but that's just a workaround for the review)

**Comment by dkgroot** [comment]
I will recreate this pull request later tonight or tomorrow morning, base on response factory alone, will try to keep the indentation intact and leave out the timeout (scrapped) stuff.

**Comment by jacobkiers** [comment]
Great, thanks!

**Comment by dkgroot** [comment]
News PR: "Added Response Factory" #73

**Pull request closed without merging**
