### PR TITLE
Fixed an error with broken ami message

### PR DESCRIPTION
**Pull request by thomasvargiu**
This PR fixes issue #108

### CODE REVIEW

**Comment by marcelog** [comment]
Hello @thomasvargiu,

This is actually a bug in Asterisk, and should be fixed there. There are certainly a number of use cases where AMI is broken in different Asterisk versions and it doesn't make much sense to implement fixes for all of them.

Please see #61 and #108.

Best,

**Comment by thomasvargiu** [comment]
Hello @marcelog,

I think it's not the same error.

This is messages that I received from Asterisk:

```
Event: BridgeEnter
Privilege: call,all
BridgeUniqueid: 8fd6434d-3079-459e-9ee2-5aa69b63dd20
BridgeType: basic
BridgeTechnology: simple_bridge
BridgeCreator: <unknown>
BridgeName: <unknown>
BridgeNumChannels: 2
Channel: SIP/TRUNK-0017d8a2
ChannelState: 6
ChannelStateDesc: Up
CallerIDNum: xxxxxxxxxxx
CallerIDName: CID:xxxxxxxxxxx
ConnectedLineNum: xxxxxxxxxxx
ConnectedLineName: <unknown>
AccountCode:
Context: macro-dialout-trunk
Exten: s
Priority: 1
Uniqueid: 1480410362.10133002

ame: CID:xxxxxxxxxxx
AccountCode:
Context: macro-dialout-trunk
Exten: s
Priority: 23
Uniqueid: 1480410361.10132991
Variable: BRIDGEPEER
Value: SIP/TRUNK-0017d8a2

Event: VarSet
Privilege: dialplan,all
Channel: SIP/714-0017d8a0
ChannelState: 6
ChannelStateDesc: Up
CallerIDNum: xxxxxxxxxxx
CallerIDName: <unknown>
ConnectedLineNum: xxxxxxxxxxx
ConnectedLineName: CID:xxxxxxxxxxx
AccountCode:
Context: macro-dialout-trunk
Exten: s
Priority: 23
Uniqueid: 1480410361.10132991
Variable: BRIDGEPVTCALLID
Value: 3555136e5da12f8e7e41aca324ba2eae@172.27.240.2:5060
```

You can see that an event is incomplete.

The problem is that it's a simple event, not related to an action. So the method `findResponse()` will return `false` and in the `process()` method we are not checking the value.

It's a simple unit test, if a method could return another value type, it should be tested and handled, like I did it in the PR.

**Comment by marcelog** [comment]
Oh ok. But in any case, this is still a bug in Asterisk, right? If it is, I still think this should be fixed in Asterisk so we don't have to maintain these fixes.

**Comment by thomasvargiu** [comment]
Honestly I don't know if could be a bug in asterisk or could be caused by many many events in few milliseconds.

But trying to dispatch the event introduced a bug, so I think there are two options:
- Don't dispatch an uncorrectly formatted message
- Check if it's related to an action like I did in the PR

The error mentioned in issue #108 is a bug in the code, not in Asterisk, because we know that a function could return an object or `false`, but we are not checking it and we are considering it like it will return always an object.

What do you think?

**Comment by marcelog** [comment]
It is considered to be an object to make it obvious that something went wrong. There should be no case where we get a response without an action id or a response for an action that we didn't send, so a crash is desired instead of continuing with invalid information.

I think more investigation is required before commiting code. My guess is that this is a bug in Asterisk, and that's why (and the reason explained above) I prefer not to merge this one.

If after some more research it turns out to be a PAMI code of course I'll be more than happy to merge a fix. But let's try no to commit code for a "just in case" scenario, or to compensate for Asterisk errors.

The AMI spec states that every message received should be an event or a response. In your tests you dispatch invalid AMI messages, this is not right and we should not encourage to support bad behaviors.

**Comment by thomasvargiu** [comment]
Ok, that's a perfect answer.

So the right way to refactor it should be throwing an Exception. But I think we could ignore it at the moment.

Thank you @marcelog

**Comment by marcelog** [comment]
Thank you, @thomasvargiu! It's always good to have someone to discuss these matters 👍 

Best!

**Pull request closed without merging**
