### PR TITLE
fix add event on broken ami and empty response

### PR DESCRIPTION
**Pull request by veksa**

### CODE REVIEW

**Comment by marcelog** [comment]
Hello!

Please see https://github.com/marcelog/PAMI/pull/61/ for a similar issue. 

Could you verify if this is  a broken AMI response and/or a broken AMI command? If that's the case, the solution would be to use another similar command (or set of commands) or upgrade to an asterisk version that fixes this. 

Thanks!

**Comment by veksa** [comment]
Hi, problem reproduced constantly and randomly when i call method $asterisk->process() when try to parse events by registerEventListener(), version of Asterisk is 11.15.1.

**Comment by marcelog** [comment]
Hello,

Please provide more information and a proper justification for the patch proposed. Logs for the events that cause the issue and any actions you might be sending too.

Thanks.

**Comment by marcelog** [comment]
Closed due to lack of activity

**Pull request closed without merging**
